### ISSUE TITLE
Error on QGIS 3.22

### ISSUE THREAD

**Issue by katagen** [lmotta/catalog-on-the-fly#3]
I update frome QGIS 3.16 to 3.22. But unfortunaltly, when I try to install the plugin Catalog on the fly, I always have this error:
Impossible de charger l'extension 'catalogotf_plugin' provoque une erreur lors de l'appel à sa méthode initGui() 

TypeError: decorated slot has no signature compatible with layerWasAdded(QgsMapLayer*) 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\catalogotf_plugin\__init__.py", line 65, in initGui
    self.dock = DockWidgetCatalogOTF( self.iface )
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\catalogotf_plugin\catalogotf.py", line 126, in __init__
    self.process = ProcessCatalogOTF( self )
  File "C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\catalogotf_plugin\catalogotf.py", line 302, in __init__
    self.project.layerWasAdded.connect( self.addedLayer )
TypeError: decorated slot has no signature compatible with layerWasAdded(QgsMapLayer*)

Version de Python : 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Version de QGIS : 3.22.8-Białowieża Białowieża, 8d5e9761df 

Chemin Python :
C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TomBio
C:/PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS32~1.8\bin\python39.zip
C:\PROGRA~1\QGIS32~1.8\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib
C:\PROGRA~1\QGIS32~1.8\bin
C:\PROGRA~1\QGIS32~1.8\apps\Python39
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\Pythonwin
C:/Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BioDispersal
C:\Users/stoant/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\BioDispersal\qgis_lib_mc
C:\Users\stoant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\stoant\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:/Users/stoant/Desktop

**Comment by katagen** [comment]
I found a solution on [https://gis.stackexchange.com/](https://gis.stackexchange.com/questions/435053/qgis-and-plugin-catalog-on-the-fly)

**Comment by AlisterH** [comment]
At least on recent versions of QGIS it's actually that line 302 which should be deleted.
